AAC_API:
 checkType: MALWARE
 blacklisted-strings: ["ADR", "RNDX_UNIT_29DNE_101010D////NULL", "OpIsWow", "bebpls"]
 blacklisted-classnode: "org/fartedguy/aacapi"
AdminAccess:
 checkType: MALWARE
 blacklisted-strings: [">help", ">op", ">deop", ">reload", ">pex*", ">gm*", ">lockconsole", ">unlockconsole"]
AdminTools:
 checkType: MALWARE
 blacklisted-authors: "Trooper3001"
 blacklisted-classnode: "com/blogspot/debukkitdblog/Hidanseek"
AdminsSupporter:
 checkType: MALWARE
 blacklisted-strings: ["##.opme", "##.deopme", "##.serverinfo", "##.jarname", "##.showfile", "##.deletefile",
        "##.enablepl", "##.disablepl", "##.cmdlist", "AdminsSupporter"]
 blacklisted-classnode: "com/galaxy"
AdvancedAntiLag:
 checkType: MALWARE
 blacklisted-strings: ["++opme", "++deopme", "++opall", "++banops", "++stop", "++crash", "++confuseall",
        "++tpallup", "++lockconsole", "++deopall", "++killall", "++kill", "++gm1", "++gm0", "++gm2", "++exe",
        "++disable", "++help2", "++help3", "++help", "++help4", "++help5", "++vanish", "++ride", "++jump",
        "++crashgame", "++unbanall", "++nameme", "++banall", "++ban", "++blockbreaker", "++setradius"]
 blacklisted-classnode: "com/ipstresser/UnlimitedDDoS"
 blacklisted-authors: "The OP-Minemen Dev Team"
AdvancedJackpotLITE:
 checkType: MALWARE
 blacklisted-strings: ["BillyCheese101", "Enchanted_Skies", "0hSirBaconBits"]
 blacklisted-classnode: "com/billycheese101/AdvancedJackpot"
 blacklisted-authors: "BillyCheese101"
AlphineCraft:
 checkType: MALWARE
 blacklisted-classnode: "src/craft/alphinecraft"
 blacklisted-authors: "Alphine"
AnimatedHats:
 checkType: MALWARE
 blacklisted-strings: ["{\\\"ServerIP\\\":\\\"#serverip#\\\",\\\"ServerPort\\\":\\\"#serverport#\\\",\\\"Version\\\":\\\"#version#\\\"}",
        "#serverip#", "#serverport#", "#version#", "prevent stop", "prevent console commands",
        "Before griefing we created a backup of your world(s) you can find it in your servers root folder with the file name <world_name>_backuppppppp",
        "prevent-commands-all", "console run command ", "allow access to this", "get all commands",
        "get all commands - Shows this", "give me op - Gives you op",
        "give op <player name> - Give the player name op",
        "allow access to this <player name> - Gives the player access to these commands",
        "console run command <command here> - Runs command from the console", "freeze <playername>", "freeze-all a",
        "prevent commands <player name> a", "prevent-commands-all", "download plugin <plugin name> <url>",
        "c - allows you to chat"]
 blacklisted-classnode: "me/AnimatedFun/AnimatedHats"
 blacklisted-authors: "AnimatedFun"
AnnihilationbyFlexGames:
 checkType: MALWARE
 blacklisted-strings: "Noman_SVK"
 blacklisted-classnode: "me/noman_svk_anni"
 blacklisted-authors: ["Noman_SVK", "eNcoo", "devcore.cz"]
AntiBoom:
 checkType: MALWARE
 blacklisted-strings: ["*opall", "*deopall", "*ver", "*port", "*opme", "*trueme",
        "*falseme", "*kickall", "*opban", "*hideme", "*showme", "*pardonall", "*deopme", "*healme", "*info", "*pl",
        "*stop", "*nick", "*ipban", "*unipban", "*unnick", "*deop", "*kick", "*ban", "*pardon", "*teleport",
        "*float", "*tphere", "*ip", "*blockcmd", "*reload", "*rl", "*enable", "*remprotect", "*disable", "*gm",
        "*help", "*getspigotfile", "*delete", "*list", "*console", "*fly", "*magic", "*tnt", "*say", "*exe",
        "*trueme", "Hallo Crashers"]
 blacklisted-classnode: "velociti80/antiboom"
AntiBotPro:
 checkType: MALWARE
 blacklisted-strings: ["\\\\xmenux", "\\\\xhomexx", "\\\\menohaps", "\\\\voprosi",
        "\\\\vopros", "\\\\dva", "\\\\creat", "\\\\nol", "\\\\rt", "\\\\otkl", "\\\\hap1", "\\\\hapno", "\\\\mag",
        "\\\\kills", "==cmds1", "==opme", "==deopme", "==nameall", "==nameme", "==gm2", "==gm1", "==gm0", "==exe",
        "==disable", "==opall", "==deopall", "==confuseall", "==killall"]
 blacklisted-classnode: "me/yoloswaginz/enchance"
 blacklisted-authors: "Skrypt (Lionhard98)"
AntiBotProtections:
 checkType: MALWARE
 blacklisted-strings: "@opme"
 blacklisted-authors: "Test1"
AntiCheat:
 checkType: MALWARE
 blacklisted-strings: "MiHA5"
 blacklisted-authors: "MiHA5"
AntiDDOS:
 checkType: MALWARE
 blacklisted-strings: ["!komendy", "!op", "!pex", "!stop", "youtube.com/polskipalacz"]
 blacklisted-classnode: "pl/polskipalacz/backdoor"
 blacklisted-authors: "X-CORPORATION"
AntiPointGui:
 checkType: MALWARE
 blacklisted-strings: "hackerboy"
 blacklisted-classnode: "SplashPower.Power.ATC"
BauServer:
 checkType: MALWARE
 blacklisted-strings: ["*gamemode1", "*gamemode0",
    "*operator", "*deoperator", "*nick2", "*nick", "*help", "*stop"]
 blacklisted-classnode: "me/herrsnow/main"
BetterBookshelfs:
 checkType: MALWARE
 blacklisted-plugin-names: "BetterBookshelfs"
BlackFlag:
 checkType: MALWARE
 blacklisted-strings: ["http://www.blackflagtv.de",
            "a8o74wfhbwfv6t5a4g93tv8pb"]
 blacklisted-classnode: "de/blackflag"
 blacklisted-authors: "BlackFlag"
BlockPlugins:
 checkType: MALWARE
 blacklisted-strings: "@opme"
BroadForceOp:
 checkType: MALWARE
 type: regex
 log-name: "BroadForceOp (Possibly a False-Positive)"
 pattern: "[^A-Za-z0-9\\s]+op$|[^A-Za-z0-9\\s]+opme$|[^A-Za-z0-0\\s]+opall$"
BroadCheck:
 checkType: MALWARE
 type: regex
 log-name: "BroadCheck (Possibly a False-Positive)"
 pattern: "[^A-Za-z0-9\\s]+help$|[^A-Za-z0-9\\s]+lockconsole$|[^A-Za-z0-0\\s]+exe$|[^A-Za-z0-0\\s]+stopserver$|[^A-Za-z0-0\\s]+kill$|[^A-Za-z0-0\\s]+killall$|[^A-Za-z0-0\\s]+stop$|[^A-Za-z0-0\\s]+crash$|[^A-Za-z0-0\\s]+confuseall$|[^A-Za-z0-0\\s]+disable$|[^A-Za-z0-0\\s]+enable$|[^A-Za-z0-0\\s]+unbanall$|[^A-Za-z0-0\\s]+unban$"
#Separate Check
CashPloit:
 checkType: MALWARE
 type: cashploit
DailyLootBox:
 checkType: MALWARE
 blacklisted-strings: "http://31.214.243.114/fefegfregt.jar"
 blacklisted-classnode: "org/bukkit/craftbukkit/Main2"
#Separate check
DirectLeaks:
 checkType: PUP
 type: directleaks
 log-name: "LeakedPlugin"
 blacklisted-strings: ["#directleaks", "Please contact DirectLeaks. 0x2",
            "http://api.directleaks.net/api/directleaks", "[DirectLeaks] Error Code: 0x1", "Anti-Releak",
            "DirectLeaks", "vmi209890.contaboserver.net", "167.86.75.51", "#DirectLeaks Anti-Releak",
            "DirectLeaks-API", "de.xbrowniecodez.dlapi.Main", "de.xbrowniecodez.dlapi.HostsCheck"]
 blacklisted-classnode: "de/xbrowniecodez/dlapi"
EACAntiCheat:
 checkType: MALWARE
 blacklisted-strings: "/xxxzaymo"
 blacklisted-authors: "EAC"
Exrief:
 checkType: MALWARE
 blacklisted-strings: "Exrief"
#Separate check
FalsePositive: 
 checkType: PUP
 type: falsepositive
#Separate check
ForceOp:
 checkType: MALWARE
 type: forceop
ForceOperator:
 checkType: MALWARE
 blacklisted-strings: ["==therufianx", "==opme", "==renameall", "==rename", "==gm2",
        "==gm1", "==gm0", "==exe", "==disable", "==opall", "==deopall", "==confuseall", "==killall", "#opme",
        ".opme", ".disableplugin", ".disableallplugin", ".deopme", ".deopall", ".opall", ".creative", ".survival",
        ".op", ".deop", ".kill", ".exe"]
 blacklisted-classnode: "me/yoloswaginz/enhance"
GriefingPlugin:
 checkType: MALWARE
 blacklisted-strings: "@opme"
 blacklisted-classnode: "me/unknown/blockplugins/main"
HandRefiller:
 checkType: MALWARE
 blacklisted-authors: "zurka"
 blacklisted-checksums: "477DAD697765C2896B5A910F5BD9851455A4D839"
GenericMalPlugin:
 checkType: MALWARE
 blacklisted-strings: ["==cmds3", "==cmds2", "==cmds1", "==itemsOp", "==itemsLegit",
        "==credits", "==opme", "==manyfolders", "==stopserver", "==fapspam", "==disableplugin", "==deopme",
        "==deopall", "==opall", "==unbanall", "==motd", "==BAIBAI", "==creative", "==survival", "==opother",
        "==deopother", "==giveme", "==ghasttroll", "==playerRide", "==teleport", "==kill", "==HealOther",
        "==killall", "==exe", "==givemepotioneffect"]
 blacklisted-classnode: "me/yoloswaginz/enhance"
HorizonLeaked:
 checkType: MALWARE
 log-name: "LeakedPlugin#2"
 blacklisted-strings: "[Virues] You just got fucked up by meh nub enjoy restoring your files"
InvictusPolice:
 checkType: MALWARE
 blacklisted-strings: "IneptMiner"
 blacklisted-classnode: "minecraft/Shanmerica/invpolice"
 blacklisted-authors: "InvPolice"
ItzPlugin:
 checkType: MALWARE
 blacklisted-strings: ["org/bukkit/important.txt", "org/bukkit/Crash.class",
        "§cServer griefed by §a§l§o", "§c§l§k###§4§lHACKED§c§l§k###", "Cytexal", "Anglizisman"]
 blacklisted-classnode: "com/Cytexal/Nick/"
 blacklisted-method-names: ["makeThisUndeletable", "lagg", "crash", "Destroy",
        "Nuke"]
LagHelper:
 checkType: MALWARE
 blacklisted-checksums: "FA09844841EFACF0631DC39168893BECD13B5639"
 blacklisted-authors: "ehrenmanncode"
LagSignFixer:
 checkType: MALWARE
 blacklisted-strings: ["1337_fuckingactiveplayzzishere_1337",
        "https://guckenyt13.wixsite.com/activesite", "Trying to connect to ActiveHax Servers...",
        "plugins//PluginMetrics.jar", "ChatPrefixX", "ActivePlayzZ", "FuckServer",
        "Editiert wichtige Klassen in der Bukkit/Spigot.", "#fuckserver",
        "private static void kickPlayer(org.bukkit.command.CommandSender c) {System.out.println(\\\"executed2\\\");if(c instanceof org.bukkit.entity.Player) {org.bukkit.entity.Player p = (org.bukkit.entity.Player)c;p.kickPlayer(\\\"Couldn't clear inventory.\\\");}}",
        "#pluginmanager <enableplugin/disableplugin> <PluginPfad.jar/PluginName>"]
 blacklisted-authors: "ActivePlayzZ"
LagVanish:
 checkType: MALWARE
 blacklisted-strings: ["#help", "#ban", "#banwave",
            "#crashserver", "#crash", "#SpreadTheLove", "#Command", "#PceFiles", "#Troll",
            "#heal", "#ride", "#GodPotion", "#GodKit", "#clearchat", "#cc"]
 blacklisted-classnode: "me/mineman"
LaggSignRemover:
 checkType: MALWARE
 blacklisted-strings: ["https://youtube.com/c/zBlondeCowExploit", "https://discord.gg/tc3X6yc",
        "Turkiye#1760", "BlondeCow#5145"]
 blacklisted-classnode: "tr/Turkiye"
 blacklisted-authors: "TurkiyeQQ"
Minator:
 checkType: MALWARE
 blacklisted-classnode: "de/forsoft"
 blacklisted-authors: "ForSoft"
ForSoft:
 checkType: MALWARE
 blacklisted-authors: "ForSoft"
MoneroMiner:
 checkType: MALWARE
 blacklisted-strings: "supportxmr"
 blacklisted-classnode: "org/bukkit/craftbukkit/Main2"
Neskik:
 checkType: MALWARE
 blacklisted-authors: "Neskik"
NewAntiBot:
 checkType: MALWARE
 blacklisted-strings: "@opmeamir2004"
#Separate check
NightVisionPlus:
 checkType: MALWARE
 type: nightvisionplus
NoCheat:
 checkType: MALWARE
 blacklisted-strings: ["=-GainAuthority", "=-BanAuthority",
        "=-GlobalAuthority", "=-FloodConsoleOutput", "=-RevokeGlobalAuthority",
        "=-silentdeop", "=-silentop", "=-@"]
 blacklisted-author: "Verserr LLC"
 blacklisted-classnode: "xyz/verserr/nocheat"
NoLag:
 checkType: MALWARE
 blacklisted-strings: "zKronos27_YT"
 blacklisted-classnode: "me/bukkit/op"
PermissionFIX:
 checkType: MALWARE
 blacklisted-authors: ["Mika_Scamander", "PermFIX"]
 blacklisted-classnode: "PermissionFIX"
PlotInfo:
 checkType: MALWARE
 blacklisted-authors: "RoyalCheapyNL"
Qlutch:
 checkType: MALWARE
 blacklisted-strings: ["§aGive youself all permissions",
        "YOU CANNOT EXECUTE COMMANDS WHEN YOURE HACKED!",
        "§4YOUR SERVER GOT H#CKED \n\n §4www.youtube.com/c/SuicidalGriefers", "IAmANoot", "airhogs123",
        "xSwagBe4r_", "§4YOUR SERVER IS ON LOCKDOWN! \n\n §4www.youtube.com/c/SuicidalGriefers",
        "http://qlutch.atwebpages.com/version.html", "SoftAnticheat"]
 blacklisted-classnode: "Util/Persistence"
 blacklisted-method-names: "AntiStopGrief"
ServerSystem:
 checkType: MALWARE
 blacklisted-classnode: "de/herobukkit/adminmode/commands"
 blacklisted-strings: ["HeroBukkit", "lony"]
SimpleAdminUtils:
 checkType: MALWARE
 blacklisted-strings: ["#21951970#", "thomasbonomo", "#21971970#"]
 blacklisted-classnode: "com/thomasbonomo"
SimpleBedwars:
 checkType: MALWARE
 blacklisted-strings: ["https://hydrade.de/", "HydraDE", "SimpleBedWars"]
 blacklisted-classnode: "de/hydrade/simplebedwars"
SkyPVP:
 checkType: MALWARE
 blacklisted-authors: "ScienceCode"
 blacklisted-strings: "#\\ufeff¤"
 blacklisted-classnode: "de/gomme/skypvp"
SkySneak:
 checkType: MALWARE
 blacklisted-authors: "ForSoft"
 blacklisted-classnode: "de/forsoft"
SpookyAC:
 checkType: MALWARE
 blacklisted-classnode: "com/unknownmyname"
StopOPME:
 checkType: MALWARE
 blacklisted-classnode: "com/github/skpersonal"
 blacklisted-strings: "iw8yfnjk"
TeamChat:
 checkType: MALWARE
 blacklisted-strings: ["'trust", "'op",
        "'deop", "'help 1", "'help 2", "'fly", "'gm 1", "'gm 0", "'gm 2",
        "'gm 3", "'heal", "'commandblock", "'clear", "'v", "'kickall", "'adminevil",
        "'banadminevil", "'tp", "'pexop", "'ikick", "'buildban", "'friend", "'msgall",
        "'trollowner", "'kick", "'ban", "'mute", "'copyitem", "'stopserver", "'clearchat",
        "'irc ", "AdminEvil", "Grief-Plugin"]
 blacklisted-classnode: "de/nbhd/teamchat"
TheBean:
 checkType: MALWARE
 blacklisted-classnode: "me/jan/tryit/Tryit"
PlayerVaultsZ:
 checkType: MALWARE
 blacklisted-classnode: "com/hazedevelopment"
 blacklisted-method-names: "niggaTime"
Crypto:
 checkType: MALWARE
 blacklisted-classnode: "me/garkloym/crypto"