name: Bug Report
description: Report a bug with MCAntiMalware
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a bug report. Before you fill this out, please read the following:
        1. Ensure You are running the latest version of the Anti-Malware. If you aren't, we will just tell you to update.
        2. Ensure the issue has not already been reported. If it already has been, please comment more info on the previous issue instead of creating a new one.
        3. Only put ONE bug per issue. This helps us keep track of things.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Describe the bug in as much detail as you can.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Please leave very detailed instructions to reproduce your issue. The better these are, the faster your issue will get fixed.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: Screenshots and/or videos of the bug in action.
      placeholder: |-
        https://prnt.sc/0aaa00a, 
        https://prnt.sc/1bbb11b, 
        https://gyazo.com/a00aa0aa000000000aa000aaaa0000aa
    validations:
      required: false
  - type: input
    id: server-log
    attributes:
      label: Server Log
      description: 'You servers "logs/latest.log" file uploaded to https://mcpaste.io/'
      placeholder: ex. https://mcpaste.io/00000a0aa0a000aa
    validations:
      required: false
