blank_issues_enabled: false
contact_links:
  - name: "Get in touch with our support team"
    url: "https://discord.gg/jMEsq4zHVA"
    about: "Need help using the Anti-Malware? Join our Discord Server for help!"
