name: False-Positive report
description: Report a False-Positive
labels: ["False Positive"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a false-positive report. Before you fill this out, please read the following:
        1. Ensure You are running the latest version of the Anti-Malware. If you aren't, we will just tell you to update.
        2. Ensure the issue has not already been reported. If it already has been, please comment more info on the previous issue instead of creating a new one.
        3. Only put ONE bug per issue. This helps us keep track of things.
  - type: input
    id: detection-string
    attributes:
      label: Detection String
      description: Provide the detection string
      placeholder: ex. Spigot.MALWARE.Antieffects.A Class Path: com/example/Example ; SourceFile/Line Example.java/-1
    validations:
      required: true
  - type: input
    id: resource-url
    attributes:
      label: Resource URL
      description: Provide the resource url
    validations:
      required: true
