name: Feature Request
description: Suggest a feature
title: "[Feature Request]: "
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a feature request. Before you fill this out, please read the following:
        1. Ensure You are running the latest version of the Anti-Malware. If you aren't, we will just tell you to update.
        2. Ensure the feature has not already been suggested. If it already has been, please comment more info on the previous issue instead of creating a new one.
        3. Only put ONE feature per issue. This helps us keep track of things.
  - type: textarea
    id: bug-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
